print('Практическая работа по уроку "Организация программ и методы строк."')
my_string = input('Введите произвольный текст ')
print('Ваш текст состоит из', len(my_string), 'символов')
print(my_string .upper())
print(my_string .lower())
print(my_string .replace(' ', ''))
print(my_string[0])
print(my_string[-1])
